#!/usr/bin/env bash

rulinered="\033[4;31;40m"
lyon="\033[36;40m"
red="\033[31;40m"
magneta="\033[35;40m"
none="\033[0m"
bold="\033[1m"

echo -e "\t\tPowered by"
echo -e $red $bold "\t\t\033[5mMaerih&Walobwa\033[0m"



chooseOption() {
	select option in "Generally clear any evidence" "clear logs for  user $USER" "Clear bash history and permenently disable it" "exit"
	do
		case $option in
			"Generally clear any evidence") general;;
			"clear logs for  user $USER" ) logs;;
			"Clear bash history and permenently disable it") Istory;;
			"exit") exit;;
			*) echo "Invalid argument...choose from menu";;
		esac
	done
}

#general logs deletion generator



Istory () {

	$(sudo shred -f -n 20 ~/.bash_history)
	echo "[+] ~/bash_history shreded."

	$(sudo shred -f -n 20 ~/.zsh_history)
	echo "[+] ~/.zsh_history shreded."

	history -c 
	echo "[+] history cleared."
}
Istory


general () {
	echo "[+] Shredding log files for $USER"
	sudo shred -fz -n 10 /var/log/* 2>>errors.txt

	echo "[+] Disabling logging system"
	service rsyslog stop

	echo "[+] Deleting history"
	export HISTFILESIZE=0
        export HISTSIZE=0
	echo "[+] Deleted history"

	echo "[+] Shredding .bash_history file"
	sudo shred -f ~/.bash_history
	sleep 2
	echo "[+] Shredding .zsh_history file"
	sudo shred -f -n 20 ~/.zsh_history
	sleep 1
	echo "[+] Disabaling history"
	shopt -ou history
}
general



